name: ppo

params:
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: ${oc.select:env.ppo.actor_mlp.units, [64, 64]}
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: nn/${env.name}_ppo.pth

  config:
    name: ${env.name}_ppo
    env_name: ${env.name}
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: ${oc.select:env.ppo.lr, 3e-4}
    lr_schedule: adaptive
    lr_threshold: 0.008
    kl_threshold: 0.008
    score_to_win: 2000000000 # never stop training
    max_epochs: ${oc.select:env.ppo.max_epochs, 5000}
    save_best_after: ${oc.select:env.ppo.save_best_after, 100}
    save_frequency: ${oc.select:env.ppo.save_frequency, 400}
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    num_actors: ${oc.select:env.ppo.num_actors, 2048}
    horizon_length: ${oc.select:env.ppo.horizon_length, 32}
    minibatch_size: ${oc.select:env.ppo.minibatch_size, 16384}
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001

    player:
      games_num: ${oc.select:env.player.games_num, 24}
      num_actors: ${oc.select:env.player.num_actors, 3}
      determenistic: True
      print_stats: True
