name: df_hopper
env_name: HopperEnv

config:
  _target_: dflex.envs.HopperEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 1024
  episode_length: 1000
  no_grad: ??? # decided based on algorithm
  stochastic_init: True
  MM_caching_frequency: 4
  early_termination: True
  termination_height: -0.45
  termination_angle: 0.524 # pi/6
  termination_height_tolerance: 0.15
  termination_angle_tolerance: 0.05
  height_rew_scale: 1.0
  action_penalty: -1e-1

  # Bundling
  bundle: False
  num_samples: 10
  sigma: 10.0
  bundle_seed: 0

  contact:
    ke: 2e4  # Nominal stiffness for elastic contact
    kd: 2e3  # Nominal damping for elastic contact
    kf: 1e3  # Nominal friction for elastic contact
    mu: 0.9  # Nominal friction coefficient for elastic contact

  # Domain randomization
  dr: False
  domain_randomization:
    bodies: [5]  # Randomize the foot and the ground (foot is body 5 in dflex)
    # Nominal ke=2e4
    # ke_range: [1e3, 1e5]
    ke_range: [8e3, 5e4]
    # Nominal kd=2e3
    # kd_range: [1e2, 1e4]
    kd_range: [1e3, 3e3]
    # Nominal kf=1e3
    # kf_range: [1e2, 1e4]
    kf_range: [8e2, 3e3]
    # Nominal mu=0.9
    # mu_range: [0.5, 1.0]
    mu_range: [0.7, 1.0]

mujoco:
  config:
    # Sim-to-sim transfer to mujoco
    _target_: sim2mujoco.envs.HopperMujocoEnv
    alg: ${alg.name}
    render: True
    num_games: 10
    num_envs: 1
    device: ${general.device}


shac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 500
  save_interval: 100
  target_critic_alpha: 0.99
  actor_mlp:
    units: [400, 200, 100]
  critic_mlp:
    units: [400, 200, 100]

ahac:
  actor_lr: 2e-3
  critic_lr: 4e-3
  max_epochs: 500
  jacobian_norm: 1.0
  grad_norm: null
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 100

ppo:
  max_epochs: 500
  lr: 5e-4
  minibatch_size: 32768
  num_actors: 4096
  horizon_length: 32
  save_frequency: 50
  save_best_after: 50
  actor_mlp:
    units: [400, 200, 100]

sac:
  max_epochs: 500
  batch_size: 2048
  num_actors: 64
  save_frequency: 500
  save_best_after: 500
  actor_critic_mlp:
    units: [128, 64, 32]

# Note SVG doesn't like floats so we use ints
svg:
  num_train_steps: 11000000 # 11M
  replay_buffer_capacity: 1000000
